### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by thomas-allard** [thomas-allard/datafrac#1]
*1. Elastic*

**Theory**
- [x] Finalize PDEs 
- [x] Formulate derivatives and other PINN requirements

**Abaqus**
- [x] Piece out simulation parameters
    E = 210 GPa, nu=0.3,
- [x] Extract field output
    - [x] Displacement components: ux, uy
    - [x] Stress components: Mises, S11, S22, S12
    - [x] Strain components: NE11, NE22, NE12
- [x] Extract nodal coordinates

**Python**
- [x] Determine best data format for data
    - [x] Creating an xarray DataSet works in an interactive python job, but it won't save to netCDF for some reason...
    - [x] Probably need to pad all the step numbers with zeros so they sort correctly
- [x] Parse out Yang's PINN code
- [x] Implement PINN

**Questions**
- [x] How do we get Haghighat et al. PINN to work for our case? Their lambda and mu are 1 and 0.5, respectively, while ours are 120 and 80.
- [ ] 

**Goals**
- [x] Implement PINN on purely elastic system
    - [x] Discover elastic parameters - no noise
    - [ ] Discover elastic parameters - with noise

*2. Fracture*
**Theory**
- [ ] Finalize PDEs 
- [ ] Formulate derivatives and other PINN requirements

**Abaqus**
- [x] Piece out LEFM XFEM simulation parameters
    E = 210 GPa, nu=0.3, sig_max (maximum principal stress)=220MPa, Gf (fracture energy) = 42,200 N/m
- [ ] Figure out how to calculate crack length through duration of the simulation
- [x] Extract field output again
    - [x] Displacement components: ux, uy
    - [x] Stress components: Mises, S11, S22, S12
    - [x] Strain components: NE11, NE22, NE12
- [x] Extract nodal coordinates

**Python**
- [ ] Implement PINN for fracture

**Goals**
- [ ] Implement PINN on Mode I system - Discover parameters
    - [ ] Failure criteria (fix elastic parameters) - no noise
    - [ ] All four - no noise
    - [ ] Failure criteria (fix elastic parameters) - with noise
    - [ ] All four - with noise
- [ ] Implement PINN on Mode II system (STRETCH)
- [ ] Implement PINN on Mixed mode system --> predict KI and KII for a given crack? (STRETCH)

* 3. Final Deliverables
- [ ] Write paper, due April 28th
- [x] Make presentation, presenting April 26th, last slot, 20-25 minutes

**Comment by thomas-allard** [comment]
** From Meeting 4/6/2022 **
From Me to Everyone 04:05 PM
https://github.com/thomas-allard/datafrac/issues/1
https://mechanicalc.com/reference/fracture-mechanics
From Me to Everyone 04:20 PM
https://www.efunda.com/formulae/solid_mechanics/mat_mechanics/calc_elastic_constants.cfm#calc
From Me to Everyone 04:26 PM
https://www.continuummechanics.org/
^ solid mechanics background
From Me to Everyone 04:35 PM
http://ceae-server.colorado.edu/v2016/
search: xfem -> abaqus benchmarks guide ->1.19.1 Crack propagation of a single-edge notch simulated using XFEM
XFEM-based LEFM approach: crackprop_model_lefm_xfem_cpe4.inp
From Me to Everyone 04:48 PM
https://www.sciencedirect.com/science/article/pii/S0045782516300238?via%3Dihub
From Me to Everyone 04:55 PM
http://kgut.ac.ir/useruploads/1555217673573rxl.pdf
